using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace Torneo_Anual_Golf_2016
{
    public partial class frm_tiros : DevExpress.XtraEditors.XtraForm
    {
        public frm_tiros()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            tirosTableAdapter1.Fill(database_shootoutDataSet1.Tiros);
        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void tirosBindingNavigatorSaveItem_Click(object sender, EventArgs e)
        {
            this.Validate();
            this.tirosBindingSource.EndEdit();
            this.tableAdapterManager.UpdateAll(this.database_shootoutDataSet);

        }

        private void frm_tiros_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'database_shootoutDataSet.Tiro_Actual' table. You can move, or remove it, as needed.
            this.tiro_ActualTableAdapter.Fill(this.database_shootoutDataSet.Tiro_Actual);
            // TODO: This line of code loads data into the 'database_shootoutDataSet.Tiros' table. You can move, or remove it, as needed.
            this.tirosTableAdapter.Fill(this.database_shootoutDataSet.Tiros);


            Timer tmr = new Timer();
            tmr.Interval = 1000;//ticks every 1 second
            tmr.Tick += new EventHandler(tmr_Tick);
            tmr.Start();

        }
        private void tmr_Tick(object sender, EventArgs e)
        {
            LblLocalTime.Text = DateTime.Now.ToString("HH:mm:ss");
            //LblUTCTime.Text = DateTime.UtcNow.ToString("MM/dd/yyyy HH:mm:ss");
        }
    }
}